
modLoader="javafml" #mandatory
loaderVersion="[4,)" #mandatory
license="MIT + CC-BY-4.0"

[[mods]] #mandatory
modId="irons_apothic" #mandatory
version="2.2.0" #mandatory
displayName="Iron's Apothic" #mandatory
authors="MuonR" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''Compatibility between Apotheosis and Iron's Spells 'n Spellbooks'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
[[mixins]]
config="irons_apothic.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.irons_apothic]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.irons_apothic]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1, 1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.irons_apothic]]
modId="apotheosis"
mandatory=true
versionRange="[8.4.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.irons_apothic]]
modId="irons_spellbooks"
type="required"
versionRange="*"
ordering="NONE"
side="BOTH"

